name: 编译群晖Jun's Mod引导

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  #schedule:
  #   - cron: '*/20 * * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
        
    
           
      - name: 发布固件
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          name: 群晖引导
          tag_name: test
          body: 测试固件
          files: user_config.json

          
      - name: delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3
